export enum ActionType {
    FETCH_ALL = "FETCH_ALL",
    FETCH_USER_POST = "FETCH_USER_POST",
    FETCH_ONE_POST = "FETCH_ONE_POST",
    CREATE_POST = "CREATE_POST",
    DELETE_POST = "DELETE_POST",
    SIGN_IN = "SIGN_IN",
    SIGN_UP = "SIGN_UP",
    LOG_OUT = "LOG_OUT",
    UPDATE_USER = "UPDATE_USER",
    DELETE_USER = "DELETE_USER",
    CHANGE_PASSWORD = "CHANGE_PASSWORD",
    USER_PROFILE = "USER_PROFILE",
    START_LOADING = "START_LOADING",
    END_LOADING = "END_LOADING",
    COMMENTS  = "COMMENTS"
}